### ISSUE TITLE
Error in core on change of sample name

### ISSUE THREAD

**Issue by rozyczko** [EasyScience/EasyDiffractionLib#29]
1. Load the PbSO4 sample
2. Change the sample name in the Sample tab to e.g. `sKKa`
3. Do something causing profile recalculation (e.g. modify one of the parameters)
3. See things break:
```
Traceback (most recent call last):
  File "D:\projects\easyScience\easyDiffractionApp\easyDiffractionApp\Logic\Proxies\Parameters.py", line 135, in editParameter
    self.logic.editParameter(obj_id, new_value)
  File "D:\projects\easyScience\easyDiffractionApp\easyDiffractionApp\Logic\Parameters.py", line 304, in editParameter
    self._updateCalculatedData()
  File "D:\projects\easyScience\easyDiffractionApp\easyDiffractionApp\Logic\Parameters.py", line 343, in _updateCalculatedData
    hkl = self._interface.get_hkl(x_array=sim.x, phase_name=phase_name)
  File "D:\projects\easyScience\easyDiffractionLib\easyDiffractionLib\interface.py", line 15, in get_hkl
    return self().get_hkl(x_array, idx=idx, phase_name=phase_name)
  File "D:\projects\easyScience\easyDiffractionLib\easyDiffractionLib\Interfaces\cryspy.py", line 255, in get_hkl
    return self.calculator.get_hkl(idx, phase_name)
  File "D:\projects\easyScience\easyDiffractionLib\easyDiffractionLib\Calculators\cryspy.py", line 461, in get_hkl
    return self.additional_data['phases'][phase_name]['hkl']
KeyError: 'sKKa'
```

**Comment by wardsimon** [comment]
Fixed in:
easyDiffractionApp [e428c596165f27cf48de2ac74ad0f9956fb234cd](https://github.com/easyScience/easyDiffractionApp/commit/e428c596165f27cf48de2ac74ad0f9956fb234cd)
easyDiffractionLib 97a8a31cdf798982b58a4f0c00151e244d27215a

**Comment by rozyczko** [comment]
things don't break anymore. :+1:
